name: reconstruction_pots
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1
  - backcall=0.2.0
  - ca-certificates=2023.11.17
  - colorama=0.4.6
  - comm=0.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=2.0.1
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - ipykernel=6.29.0
  - ipython=8.12.0
  - jedi=0.19.1
  - jupyter_client=8.6.0
  - jupyter_core=4.12.0
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - nest-asyncio=1.5.9
  - openssl=3.0.12
  - packaging=23.2
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=23.3.1
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.9.18
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pywin32=227
  - pyzmq=25.1.2
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tornado=6.2
  - traitlets=5.14.1
  - typing_extensions=4.9.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.13
  - wheel=0.41.2
  - zeromq=4.3.5
  - zipp=3.17.0
  - pip:
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - contourpy==1.2.0
      - cycler==0.12.1
      - et-xmlfile==1.1.0
      - filelock==3.9.0
      - fonttools==4.47.2
      - fsspec==2023.4.0
      - idna==3.4
      - imageio==2.33.1
      - importlib-resources==6.1.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - mpmath==1.3.0
      - networkx==3.0
      - numpy==1.26.3
      - opencv-python==4.9.0.80
      - openpyxl==3.1.2
      - pandas==2.2.0
      - pillow==10.2.0
      - pyarrow==14.0.2
      - pyparsing==3.1.1
      - pytz==2023.3.post1
      - requests==2.28.1
      - scikit-image==0.22.0
      - scikit-learn==1.4.0
      - scipy==1.11.4
      - seaborn==0.13.1
      - sympy==1.12
      - threadpoolctl==3.2.0
      - tifffile==2023.12.9
      - torch==2.1.2+cu118
      - torchaudio==2.1.2+cu118
      - torchinfo==1.8.0
      - torchvision==0.16.2+cu118
      - tqdm==4.66.1
      - tzdata==2023.4
      - urllib3==1.26.13
